#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BCyan='\033[1;36m'    
BGreen='\033[1;32m'   
NC='\e[0m'

echo -e "${BGreen}***** Running pre-commit (${BCyan}Eslint, Stylelint${BGreen}) checks... *****${NC}"

npx lint-staged --quiet --concurrent false

echo -e "${BGreen}>>> No Errors ✅ <<<${NC}"